### ISSUE TITLE
The app crashes on launch

### ISSUE THREAD

**Issue by golf1052** [golf1052/TwixelAppUniversal#2]
Originally reported [here](https://github.com/golf1052/TwixelApp/issues/10)

The app crashes on launch (it says it is loading emotes).

Windows 10, using latest version of Twixel from the store.

**Comment by golf1052** [comment]
@samtebbs33 I just pushed a new version of the app to the store. When it goes live I'll ping you again so you can see if that fixes your issue.

**Comment by SamTebbs33** [comment]
Thanks! How long does it normally take for a version to go live?

**Comment by golf1052** [comment]
Received an email two hours ago stating that it's live in the store but that it can take up to 16 hours for it to be visible to everyone. I'm seeing an update available on my side but I don't know how long it will take for you. Once you get the update please report back if the issue is resolved.

**Comment by golf1052** [comment]
@SamTebbs33 I assume the update has gone out everywhere. Please report back if the update fixed your issue.

**Comment by SamTebbs33** [comment]
There's no option to update the app at the moment, should there be? (I'm new to the Windows Store)

**Comment by golf1052** [comment]
@SamTebbs33 I'm hoping you received the update at this point (updates should auto install when they come in). Will close this issue in the next couple days unless something else comes up.
